# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    network_mode: "host"
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin

  api:
    depends_on:
      - db
    ports:
      - 8000:8000
    build: .
    network_mode: "host"
    volumes:
      - files:/files

volumes:
  files:
