# Generated by Django 5.1.5 on 2025-02-18 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_max', models.IntegerField()),
                ('per_submission_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc_short', models.CharField(max_length=255)),
                ('desc_detailed', models.CharField(max_length=511)),
                ('enroll_date_begin', models.DateField()),
                ('enroll_date_end', models.DateField()),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='files\\images\\event\\')),
                ('workload', models.IntegerField()),
                ('minimum_attendances', models.IntegerField()),
                ('maximum_enrollments', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('ActivityTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activitytype')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files\\certificates\\')),
                ('emission_date', models.DateTimeField(null=True)),
                ('eventId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_dates', to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=None, null=True)),
                ('eventDateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventdate')),
                ('enrollmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_number', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='files\\images\\principal\\')),
                ('majorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.major')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_number', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='files\\images\\professor\\')),
                ('majorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.major')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='professorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_number', models.CharField(max_length=255, unique=True)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='files\\images\\student\\')),
                ('majorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.major')),
            ],
        ),
        migrations.AddField(
            model_name='eventenrollment',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.CreateModel(
            name='ComplementaryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.IntegerField()),
                ('status', models.BooleanField(default=None, null=True)),
                ('description', models.CharField(max_length=500)),
                ('feedback', models.TextField(blank=True, max_length=500, null=True)),
                ('ActivityTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activitytype')),
                ('certificateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificate', unique=True)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
