# Generated by Django 5.1.5 on 2025-01-22 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_certificate_path_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='eventId',
        ),
        migrations.AddField(
            model_name='attendance',
            name='eventDateId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.eventdate'),
            preserve_default=False,
        ),
    ]
