# Generated by Django 5.1.5 on 2025-01-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_attendance_eventid_attendance_eventdateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
