# Generated by Django 5.1.5 on 2025-01-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complementaryactivity',
            old_name='tudentId',
            new_name='studentId',
        ),
    ]
