# Generated by Django 5.1.5 on 2025-01-22 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_tudentid_complementaryactivity_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryactivity',
            name='certificateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificate', unique=True),
        ),
    ]
