# Generated by Django 5.1.5 on 2025-01-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_certificate_file_alter_event_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementaryactivity',
            name='feedback',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
