# Generated by Django 5.1.5 on 2025-02-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_complementaryactivity_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(upload_to='files\\certificates\\'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='files\\images\\event\\'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='files\\images\\principal\\'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='files\\images\\professor\\'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='files\\images\\student\\'),
        ),
    ]
