# Generated by Django 5.1.5 on 2025-02-13 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_activitytype_name_alter_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_dates', to='api.event'),
        ),
    ]
